In [1]:
import pandas as pd
import matplotlib as plt
import numpy as np

df = pd.read_csv('mine.csv')
print(df)

    Duration         Date  Pulse  Maxpulse  Calories
0         60  2023/10/01'  110.0     130.0     409.1
1         60  2023/10/02'  117.0     145.0     479.0
2         60  2023/10/03'  103.0     135.0     340.3
3         45  2023/10/04'  109.0     175.0     282.4
4         45  2023/10/05'  117.0     150.0     405.1
5         60  2023/10/06'  103.0     125.0     300.0
6         60  2023/10/07'  110.0     135.0     374.0
7        400  2023/10/08'  114.0     133.0       NaN
8         60  2023/10/09'  112.0     126.0     193.8
9         30  2023/10/10'  102.0     147.0     234.8
10        60  2023/10/11'  100.0     129.0     375.3
11        60  2023/10/12'  109.0     131.0     345.6
12        60  2023/10/13'  103.0     136.0     239.2
13        60  2023/10/15'  120.0       NaN     240.8
14        60  2023/10/15'  120.0     100.0     240.8
15        60  2023/10/16'    NaN     101.0     243.8
16        60  2023/10/17'  127.0     102.0     380.2
17        45     20231018  142.0     103.0     241.4
18        60  2023/10/19'  151.0     104.0       NaN
19        60  2023/10/20'  162.0     105.0     300.9
20        60  2023/10/21'  100.0     106.0     280.0
21        60  2023/10/22'  103.0     107.0       NaN
22        60          NaN  130.0     108.0     230.8
23        60  2023/10/24'  134.0       NaN     239.7
24        60  2023/10/25'  132.0     110.0     236.9
25        60  2023/10/26'  135.0     118.0     278.8
26        60  2023/10/27'  137.0     119.0     212.9
27        60  2023/10/28'  138.0     121.0     345.9
28        60  2023/10/29'  139.0     122.0     345.2
29        60          NaN   92.0     125.0     380.5
30        60  2023/10/31'   94.0     126.0       NaN

In [2]:
#remove spaces

df.dropna()

    Duration         Date  Pulse  Maxpulse  Calories
0         60  2023/10/01'  110.0     130.0     409.1
1         60  2023/10/02'  117.0     145.0     479.0
2         60  2023/10/03'  103.0     135.0     340.3
3         45  2023/10/04'  109.0     175.0     282.4
4         45  2023/10/05'  117.0     150.0     405.1
5         60  2023/10/06'  103.0     125.0     300.0
6         60  2023/10/07'  110.0     135.0     374.0
8         60  2023/10/09'  112.0     126.0     193.8
9         30  2023/10/10'  102.0     147.0     234.8
10        60  2023/10/11'  100.0     129.0     375.3
11        60  2023/10/12'  109.0     131.0     345.6
12        60  2023/10/13'  103.0     136.0     239.2
14        60  2023/10/15'  120.0     100.0     240.8
16        60  2023/10/17'  127.0     102.0     380.2
17        45     20231018  142.0     103.0     241.4
19        60  2023/10/20'  162.0     105.0     300.9
20        60  2023/10/21'  100.0     106.0     280.0
24        60  2023/10/25'  132.0     110.0     236.9
25        60  2023/10/26'  135.0     118.0     278.8
26        60  2023/10/27'  137.0     119.0     212.9
27        60  2023/10/28'  138.0     121.0     345.9
28        60  2023/10/29'  139.0     122.0     345.2

In [4]:
df.dropna(inplace=True)
df.to_csv('Mine.csv', index=False)

In [5]:
#duplicates
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
8     False
9     False
10    False
11    False
12    False
14    False
16    False
17    False
19    False
20    False
24    False
25    False
26    False
27    False
28    False
dtype: bool

In [ ]:
#remove wrong formart

df['Date'] = pd.to_datetime(df['Date'], format='mixed')
#saving to the original file
df.to_csv('Mine.csv', index=False)

In [9]:
print(df)

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2023-10-01  110.0     130.0     409.1
1         60 2023-10-02  117.0     145.0     479.0
2         60 2023-10-03  103.0     135.0     340.3
3         45 2023-10-04  109.0     175.0     282.4
4         45 2023-10-05  117.0     150.0     405.1
5         60 2023-10-06  103.0     125.0     300.0
6         60 2023-10-07  110.0     135.0     374.0
8         60 2023-10-09  112.0     126.0     193.8
9         30 2023-10-10  102.0     147.0     234.8
10        60 2023-10-11  100.0     129.0     375.3
11        60 2023-10-12  109.0     131.0     345.6
12        60 2023-10-13  103.0     136.0     239.2
14        60 2023-10-15  120.0     100.0     240.8
16        60 2023-10-17  127.0     102.0     380.2
17        45 2023-10-18  142.0     103.0     241.4
19        60 2023-10-20  162.0     105.0     300.9
20        60 2023-10-21  100.0     106.0     280.0
24        60 2023-10-25  132.0     110.0     236.9
25        60 2023-10-26  135.0     118.0     278.8
26        60 2023-10-27  137.0     119.0     212.9
27        60 2023-10-28  138.0     121.0     345.9
28        60 2023-10-29  139.0     122.0     345.2

In [ ]:
#wrong data
df.loc[10, 'Duration'] = 45
#saving to the original file
df.to_csv('mine.csv', index=False)
print(df)

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2023-10-01  110.0     130.0     409.1
1         60 2023-10-02  117.0     145.0     479.0
2         60 2023-10-03  103.0     135.0     340.3
3         45 2023-10-04  109.0     175.0     282.4
4         45 2023-10-05  117.0     150.0     405.1
5         60 2023-10-06  103.0     125.0     300.0
6         60 2023-10-07  110.0     135.0     374.0
8         60 2023-10-09  112.0     126.0     193.8
9         30 2023-10-10  102.0     147.0     234.8
10        45 2023-10-11  100.0     129.0     375.3
11        60 2023-10-12  109.0     131.0     345.6
12        60 2023-10-13  103.0     136.0     239.2
14        60 2023-10-15  120.0     100.0     240.8
16        60 2023-10-17  127.0     102.0     380.2
17        45 2023-10-18  142.0     103.0     241.4
19        60 2023-10-20  162.0     105.0     300.9
20        60 2023-10-21  100.0     106.0     280.0
24        60 2023-10-25  132.0     110.0     236.9
25        60 2023-10-26  135.0     118.0     278.8
26        60 2023-10-27  137.0     119.0     212.9
27        60 2023-10-28  138.0     121.0     345.9
28        60 2023-10-29  139.0     122.0     345.2

In [30]:
#drop specific columns
#df = df.drop(['Column1', 'Column2'], axis=1)
#drop a specific column
#df = df.drop('ColumnName', axis=1)
#change and save to file directly
#df.drop(['Column1', 'Column2'], axis=1, inplace=True)
import pandas as pd
df = pd.read_csv('mine.csv')
#drop column
df.drop('Maxpulse', axis=1, inplace=True)
#save to original file
df.to_csv('mine.csv', index=False)
print(df)

    Duration        Date  Pulse  Calories
0         60  2023-10-01  110.0     409.1
1         60  2023-10-02  117.0     479.0
2         60  2023-10-03  103.0     340.3
3         45  2023-10-04  109.0     282.4
4         45  2023-10-05  117.0     405.1
5         60  2023-10-06  103.0     300.0
6         60  2023-10-07  110.0     374.0
7         60  2023-10-09  112.0     193.8
8         30  2023-10-10  102.0     234.8
9         45  2023-10-11  100.0     375.3
10        60  2023-10-12  109.0     345.6
11        60  2023-10-13  103.0     239.2
12        60  2023-10-15  120.0     240.8
13        60  2023-10-17  127.0     380.2
14        45  2023-10-18  142.0     241.4
15        60  2023-10-20  162.0     300.9
16        60  2023-10-21  100.0     280.0
17        60  2023-10-25  132.0     236.9
18        60  2023-10-26  135.0     278.8
19        60  2023-10-27  137.0     212.9
20        60  2023-10-28  138.0     345.9
21        60  2023-10-29  139.0     345.2